---
- hosts: your_slave_node
  become: yes
  tasks:
    - name: Copy the Bash script to the slave node
      copy:
        src: /path/to/deploy_test.sh  # Path to your Bash script
        dest: /tmp/deploy_test.sh   # Destination on the slave node
        mode: 0755

    - name: Execute the Bash script on the slave node
      command: /tmp/deploy_test.sh
      ignore_errors: yes  # This will continue even if the script fails

    - name: Verify PHP application accessibility
      wait_for:
        host: your_vm_ip  # Replace with your VM's IP address
        port: 80  # Assuming your PHP application runs on port 80
        state: started
